config/routes.rb
FoodWhack::Application.routes.draw do

   get "site/index"

   root 'site#welcome'

   namespace :admin do
   root :to =>'dashboard#index'
   devise_for :user
  end

  devise_for :users

  devise_for :adminusers,:controllers => { :registrations => "adminsession",:sessions => "adminregistration" } do

  end

end

app/models/adminuser.rb
class Adminuser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
        layout "admin_layout"

       before_filter :authenticate_adminuser!

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController


#----------------------------------------------------------------------
# Method for index
# ---------------------------------------------------------------------

  def index

  end

end

app/controllers/adminregistration_controller.rb
class AdminregistrationController < Devise::SessionsController



# Custom devise Method for sing out path
# ---------------------------------------------------------------------

         def after_sign_out_path_for(resource_or_scope)
      admin_root_path
     end

# Custom devise Method for sing in path
# ---------------------------------------------------------------------

      def after_sign_in_path_for(resource_or_scope)
       admin_root_path
     end

end

app/controllers/adminsession_controller.rb
class AdminsessionController < Devise::RegistrationsController


# Devise custom Methods for admin sign
#------------------------------------------------------------------------------------
        def after_sign_in_path_for(resource)
             admin_root_path
        end

# Devise custom Methods admin update path
#------------------------------------------------------------------------------------

          def after_update_path_for(resource)
         admin_root_path
         end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    #@response = JSON.parse(HTTPClient.new.get(URI.encode("https://api.instagram.com/v1/media/popular?client_id=f69d548aeb314c2997583b8cfa154691").to_s).body)["data"]
    url = ""
    @fs = JSON.parse(HTTPClient.new.get(URI.encode(url).to_s).body)["response"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/site_helper.rb
module SiteHelper
  def tag_color
    ['#1abc9c', '#2ecc71', '#3498db', '#9b59b6',
      '#34495e', '#16a085', '#27ae60', '#2980b9',
      '#8e44ad', '#2c3e50', '#f1c40f', '#e67e22',
      '#e74c3c', '#f39c12', '#d35400', '#c0392b'
    ].sample
  end
end

app/views/admin/dashboard/index.html.erb
<h2>Welcome to Foodwhack Admin </h2>

app/views/adminregistration/new.html.erb
<h2>Sign in</h2>

<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <% if devise_mapping.rememberable? -%>
    <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
  <% end -%>

  <div><%= f.submit "Sign in" %></div>
<% end %>

<%= render "devise/shared/links" %>

app/views/adminsession/edit.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
  <% end %>

  <div><%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
  <%= f.password_field :password, :autocomplete => "off" %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
  <%= f.password_field :current_password %></div>

  <div><%= f.submit "Update" %></div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete %></p>

<%= link_to "Back", :back %>

app/views/adminsession/new.html.erb
<h2>Sign up</h2>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email, :autofocus => true %></div>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.submit "Sign up" %></div>
<% end %>

<%#= render "devise/shared/links" %>

app/views/layouts/admin_layout.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodWhack Admin</title>

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#"></a>
          <div class="nav-collapse">
            <ul class="nav">

            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">

        <div id="user_nav">

        </div>
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
            <a class="close" data-dismiss="alert">x</a>
            <%= msg  %>
          </div>
        <% end %>
        <div class="span12"><%= yield %></div>

      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodwhack</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.1/leaflet.css" />
  <script src="http://cdn.leafletjs.com/leaflet-0.7.1/leaflet.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Static navbar -->
    <div class="navbar navbar-custom" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Food Whack</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a href="/" class="navbar-brand">Foodwhack</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li>
              <a href="/">HOME</a>
            </li>
            <li>
              <a href="#">BLOG</a>
            </li>
            <li>
              <a href="#">HELP</a>
            </li>
            <li>
              <a href="#">ABOUT</a>
            </li>
            <li>
              <a href="#">CONTACT</a>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="primary">
                <%= link_to(destroy_user_session_path, :method => :get, :class => 'icon-off' ) do %>SIGN OUT
                <% end %>
              </li>
            <% else %>
              <li class="inverse">
                <a href="/users/sign_in">LOGIN</a>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <div class="container">
    <%= yield %>
  </div>
  <%
     q = params[:q] || "New York"
     ll = Geocoder.search("#{q}")[0].geometry["location"]
  %>
  <script type="text/javascript">
    $(document).on('page:fetch',   function() { NProgress.start(); });
    $(document).on('page:change',  function() { NProgress.done(); });
    $(document).on('page:restore', function() { NProgress.remove(); });
    $(document).on('page:load', function() { initMap(); });
    $('.dropdown-toggle').dropdown();

    var map = L.map('map').setView([<%= ll["lat"] %>,<%= ll["lng"] %>], 12);

      L.tileLayer('http://{s}.tile.cloudmade.com/e34ecc3a72ed454588fc6e8900cd8923/997/256/{z}/{x}/{y}.png', {
        maxZoom: 18,
        attribution: ''
      }).addTo(map);

      var loc = <%= @location %>;
      var addr = <%= raw @address %>;
      console.log(loc[0][0]);
      for(var i=0;i <= loc.length; i++) {
        L.marker(loc[i]).addTo(map).bindPopup('<a href="#">'+addr[i]+'</a>');  
      }
      
      var popup = L.popup();

      function onMapClick(e) {
        popup
          .setLatLng(e.latlng)
          .setContent("You clicked the map at " + e.latlng.toString())
          .openOn(map);
      }

      map.on('click', onMapClick);

  </script>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-46704462-1', 'foodwhack.com');
    ga('send', 'pageview');

  </script>
</body>
</html>

app/views/site/index.html.erb
<div class="row">
  <div class="col-sm-9"></div>
  <div class="col-sm-3 input-group srch-inp">
    <form role="search">
      <input type="text" class="input-large form-control" name="q" value="<%= params[:q] %>"  placeholder="e.g, New York">
    </form>
  </div><!-- /input-group -->
  <div id='map'></div>
  <% if @fs.present? %>
    <% @fs["groups"][0]["items"].each_with_index do |data,i| %>
      <div class="col-md-3" style="min-height:190px;">
        <% 
          if data["categories"].present?
            img = data["categories"][0]["icon"] 
            name = data["categories"][0]["name"] 
          end
        %>
        <img src="<%= img %>">
        <div><%= data["name"] %></div>
        <div><%= name %></div>
        <h6 style="color:#D35400;"><b><%= data["location"]["address"] %></b></h6>
      </div>
    <% end %>
  <% end %>
</div>

app/views/site/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Foodwhack</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</head>
<style type="text/css">
	html { 
	  background: url(assets/bg.png) no-repeat center center fixed; 
	  -webkit-background-size: cover;
	  -moz-background-size: cover;
	  -o-background-size: cover;
	  background-size: cover;
	}
	body {
		background: #2ecc71;
	}

	h1, h2 {
		color: black;
	}

	h1{
		font-size: 190px;
	}

	.content {
		 margin: 0 auto;padding-top: 150px;position: absolute;left: 20%;top: 15%;text-align: center; width: 800px; height: 500px;border-radius: 10px;
	}
</style>
<body>
<div class="content">
	<h1>Foodwhack</h1>
	<h2>Coming Soon !</h2>
</div>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-46704462-1', 'foodwhack.com');
    ga('send', 'pageview');

  </script>
</body>
</html>